version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: some_password123
  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - "db"
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: some_password123
      DB_HOST: db
    command: ["bash", "wait-for-postgres-then-run.sh", "python", "manage.py", "test"]
